apiVersion: v1
kind: Namespace
metadata:
  name: keepalived
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config-files
  namespace: keepalived
data:
  keepalived.conf: |
    ! /etc/keepalived/keepalived.conf
    ! Configuration File for keepalived
    global_defs {
      router_id 20
    }
    vrrp_script check_apiserver {
      script "/etc/keepalived/check_apiserver.sh"
      interval 3
      weight -2
      fall 10
      rise 2
    }

    vrrp_instance VI_1 {
      state master
      interface _INT_
      virtual_router_id _RID_
      priority 10
      authentication {
        auth_type PASS
        auth_pass _PASS_
      }
      virtual_ipaddress {
        1_VIP_
      }
      track_script {
        check_apiserver
      }
    }

  check_apiserver.sh: |
    #!/bin/sh
    errorExit() {
      echo "*** $*" 1>&2
      exit 1
    }
    APISERVER_DEST_PORT=6443
    APISERVER_VIP=_VIP_
    curl --silent --max-time 2 --insecure https://localhost:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET https://localhost:${APISERVER_DEST_PORT}/"
    if ip addr | grep -q ${APISERVER_VIP}; then
      curl --silent --max-time 2 --insecure https://${APISERVER_VIP}:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET https://${APISERVER_VIP}:${APISERVER_DEST_PORT}/"
    fi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: keepalived
  labels:
    app: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      hostNetwork: true
      containers:
      - name: keepalived
        image: goacid/keepalived:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN",'NET_BROADCAST','NET_RAW']
        volumeMounts:
        - name: config
          mountPath: /etc/keepalived
      volumes:
      - name: config
        configMap:
          name: keepalived-config-files
        
